DROP TABLE IF EXISTS NEWS;
DROP TABLE IF EXISTS NEWS_CATIGORIES;

CREATE TABLE NEWS (
  ID SERIAL PRIMARY KEY,
  TITLE VARCHAR(50) NOT NULL,
  CONTENT VARCHAR(500) NOT NULL
);

CREATE TABLE NEWS_CATEGORIES (
  NEWS_ID INT NOT NULL,
  CATEGORY_ID INT NOT NULL,
  PRIMARY KEY (NEWS_ID, CATEGORY_ID)
);

INSERT INTO NEWS (id, title, content) VALUES 
(1, 'title1', 'content1'),
(2, 'title2', 'content2'),
(3, 'title3', 'content3');

INSERT INTO NEWS_CATEGORIES (NEWS_ID, CATEGORY_ID) VALUES
(1, 1),
(1, 2),
(1, 3),
(2, 2),
(2, 3),
(3, 3);